[project]
name = "ib-flex-importer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beancount>=3.1.0",
    "beangulp>=0.2.0",
    "ibflex>=0.15",
]
